eureka:
  client:
    service-url:
      defaultZone: http://eureka.gulang.work/eureka  # 设置与Eureka Server交互的地址查询服务和注册服务
  instance:
    instance-id: gateway-id
    prefer-ip-address: true

spring:
  cloud:
    config:
      name: ${spring.application.name}
      profile: dev
      uri: http://config.gulang.work